@baseUrl = http://localhost:3000/api/subscription

### 1. SUBSCRIBE (Create)
POST {{baseUrl}}/subscribe
Content-Type: application/json

{ "email": "krizia_test@example.com" }

### 2. GET ALL SUBSCRIBERS
GET {{baseUrl}}/

### 3. UNSUBSCRIBE (Update Status)
PATCH {{baseUrl}}/unsubscribe
Content-Type: application/json

{ "email": "krizia_test@example.com" }
